backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "artworks"
    label: "Œuvres"
    folder: "data"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Artiste", name: "artist", widget: "string" }
      - { label: "Année", name: "year", widget: "string" }
      - { label: "Médium", name: "medium", widget: "string" }
      - { label: "Dimensions", name: "dimensions", widget: "string" }
      - { label: "Lieu", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Code d'inventaire", name: "accession_code", widget: "string" }
      - { label: "Image (nom fichier)", name: "image", widget: "string" }
